### ISSUE TITLE
Hamburger navbar

### ISSUE THREAD

**Issue by aayusranjan** [DayMrz/Portfolio-Resume-Day#2]
Hey Day!
Good Job, you are doin great.
I went through your protfolio on phone and I saw some issues if y click on any nav-items it's hovering blue color on whole nav-container y can do hovering effect on only one items instead of whole container. Also if you do CV background color little bit less opacity or different style then it will look more pretty ig, its all my view.

**Comment by DayMrz** [comment]
Oh! 
Ayush Ranjan, thank you for pointing that out, I'm still working on it so
I will have in mind what you described above.

I appreciate you taking the time to review my portfolio. :3
